name: "Chore Wheel"
on:
  schedule:
    # run a cron job every sunday morning at 10 am cst
    - cron: "0 15 * * 0"
  # run on dispatch
  workflow_dispatch:

jobs:
  assign-chores:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - run: |
          npm install
          node index.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VB_SUB_ID: ${{ secrets.VB_SUB_ID }}
          VB_SUB_KEY: ${{ secrets.VB_SUB_KEY }}
          VB_SUB_SECRET: ${{ secrets.VB_SUB_SECRET }}
